version: '3.8'

services:
  # Dịch vụ cho ứng dụng Spring Boot
  app:
    build: .
    container_name: spring-boot-app
    # Cấu hình quan trọng: Chờ cho đến khi 'db' sẵn sàng rồi mới khởi động
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    # Cung cấp thông tin kết nối DB cho ứng dụng
    environment:
      - DB_HOST=db  # 'db' là tên của service database bên dưới
      - DB_NAME=vhoang12
      - DB_USERNAME=myuser
      - DB_PASSWORD=mypassword

  # Dịch vụ cho database MySQL
  db:
    image: mysql:8.0
    container_name: mysql-db
    # Cung cấp thông tin để khởi tạo database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vhoang12
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      # Mở cổng 3306 để có thể kết nối từ bên ngoài nếu cần
      - "3306:3306"
    volumes:
      # Gắn volume để dữ liệu không bị mất khi container khởi động lại
      - mysql-data:/var/lib/mysql
    # Cấu hình kiểm tra sức khỏe để đảm bảo MySQL đã sẵn sàng
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      interval: 10s
      retries: 10

# Khai báo volume để lưu trữ dữ liệu
volumes:
  mysql-data: