spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/vhoang12}
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    root: info
    org.hibernate.SQL: debug

# Swagger: http://localhost:8080/swagger-ui.html
